require "user.options"
require "user.plugins"
require "user.keymaps"
require "user.colorscheme"
require "user.nvim-tree"
require "user.nvim-treesitter"
require "user.lsp"
require "user.autopairs"
require "user.completion"

